apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: agenda-crud
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_NAME: agenda
  DB_USER: agenda
  DB_SSLMODE: disable

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: agenda-crud
data:
  API_BASE_URL: http://backend:3000
