apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: agenda-crud
data:
  POSTGRES_DB: "agenda"
  POSTGRES_USER: "postgres"
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: agenda-crud
type: Opaque
stringData:
  POSTGRES_PASSWORD: "postgres"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: agenda-crud
data:
  PORT: "3000"
  DB_HOST: "postgres-service"
  DB_PORT: "5432"
  DB_USER: "postgres"
  DB_NAME: "agenda"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: agenda-crud
type: Opaque
stringData:
  DB_PASSWORD: "postgres"
