version: '3.8'

services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agenda
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./backend/migrations:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile
    environment:
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=agenda
    depends_on:
      - db
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.Dockerfile
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  db-data:
